baseurl: /blog
auto: true


encoding: utf-8
markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: KillEts.Blog
url: http://killets.github.io/blog/
baseurl: http://killets.github.io/blog
feed: /atom.xml
author_info: <a href="http://killets.github.io/blog/">killets</a>
